apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-historian
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: url
      value: $STANDALONE_MQTT_URL
    - name: qos
      value: 1
    - name: retain
      value: "false"
    - name: cleanSession
      value: "false"
    - name: consumerID
      value: $STANDALONE_MQTT_CONSUMER_ID
